# build docker images using makefile

services:
  - docker

before_install:
  - docker pull wrfly/golang-alpine-build

script:
  - make img

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - if [[ "$TRAVIS_BRANCH" == "master" ]];then make push-img; fi
  - if [[ "$TRAVIS_BRANCH" == "develop" ]];then make push-dev-img; fi
