sudo: required

services:
  - docker

script:
  - make img

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make push-img ;
      docker logout;
    fi